// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State__Update_639985b94e
    {
        private State state;

        [SetUp]
        public void Setup()
        {
            this.state = new State();
        }

        [Test]
        public void Update_PositiveDeltaTime_CallsUpdateMethod()
        {
            // TODO: Replace with appropriate mock
            Mock<State> mockedState = new Mock<State>();
            this.state = mockedState.Object;

            this.state._Update(0.5f);

            mockedState.Verify(s => s.Update(It.IsAny<float>()), Times.Exactly(1));
        }

        [Test]
        public void Update_NegativeDeltaTime_DoesNotCallUpdateMethod()
        {
            // TODO: Replace with appropriate mock
            Mock<State> mockedState = new Mock<State>();
            state = mockedState.Object;

            this.state._Update(-0.1f);

            mockedState.Verify(s => s.Update(It.IsAny<float>()), Times.Never);
        }

        [Test]
        public void Update_ZeroDeltaTime_DoesNotCallUpdateMethod()
        {
            // TODO: Replace with appropriate mock
            Mock<State> mockedState = new Mock<State>();
            this.state = mockedState.Object;

            this.state._Update(0.0f);

            mockedState.Verify(s => s.Update(It.IsAny<float>()), Times.Never);
        }

        [TearDown]
        public void TearDown()
        {
            this.state = null;
        }
    }
}
