// Test regenerated by AI

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public class FiniteStateBeganEventArgs_FiniteStateChangeEventArgs_c420a1754c
    {
        private FiniteStateChangeEventArgs _finiteStateChangeEventArgs; 

        [SetUp]
        public void SetUp()
        {
            // Setup your mocked dependencies here.
        }

        [Test]
        public void FiniteStateChangeEventArgs_ValidState_ReturnsValidStateType()
        {
            // Arrange
            var requestedState = StateType.Valid;

            // Act
            _finiteStateChangeEventArgs = new FiniteStateChangeEventArgs(requestedState);

            // Assert
            Assert.AreEqual(requestedState, _finiteStateChangeEventArgs.RequestedType);
        }

        [Test]
        public void FiniteStateChangeEventArgs_InvalidState_ThrowsException()
        {
            // Arrange
            var requestedState = (StateType)999; 

            // Act & Assert
            Assert.Throws<ArgumentOutOfRangeException>(() => new FiniteStateChangeEventArgs(requestedState));
        }

        [TearDown]
        public void TearDown()
        {
            // Clean up resources, if required.
        }
    }
}
