// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k


using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test 
{
    [TestFixture]
    public class FiniteStateBeganEventArgs_FiniteStateChangeEventArgs_c420a1754c 
    {
        [Test]
        public void Constructor_Should_Set_RequestedState() 
        {
            // Arrange
            StateType requestedState = StateType.Idle;

            // Act
            FiniteStateChangeEventArgs finiteStateChangeEventArgs = new FiniteStateChangeEventArgs(requestedState);

            // Assert
            Assert.AreEqual(requestedState, finiteStateChangeEventArgs.RequestedType);
        }

        // Test for edge cases and failure scenarios
        [Test]
        public void Constructor_Should_Throw_ArgumentException_For_Null_State() 
        {
            // Arrange
            StateType requestedState = null;

            // Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(requestedState));
        }
    }
}
