// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateChangeEventArgsTests
    {
        private FiniteStateChangeEventArgs _sut;

        [SetUp]
        public void SetUp()
        {
            _sut = new FiniteStateChangeEventArgs(StateType.Initial);
        }

        [Test]
        public void FiniteStateChangeEventArgs_TransitionToInitial_ReturnsInitialState()
        {
            Assert.AreEqual(StateType.Initial, _sut.RequestedType);
        }

        [Test]
        public void FiniteStateChangeEventArgs_TransitionToFinal_ReturnsFinalState()
        {
            _sut = new FiniteStateChangeEventArgs(StateType.Final);
            
            Assert.AreEqual(StateType.Final, _sut.RequestedType);
        }

        [Test]
        public void FiniteStateChangeEventArgs_TransitionToNull_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(null));
        }
    }
}
