// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using System;
using NUnit.Framework;
using FiniteStateMachine;
using FiniteStateMachine.Test; 

namespace FiniteStateMachine.Test
{
    public class State__End_5b00770643_Test
    {
        private State__End_5b00770643 stateEnd;

        [SetUp]
        public void Setup()
        {
            stateEnd = new State__End_5b00770643();
        }

        [Test]
        public void Test_End_CalledSuccessful()
        {
            try
            {
                stateEnd._End();
                Assert.Pass(); // Pass Test if no exception is thrown
            }
            catch (Exception ex)
            {
                Assert.Fail("Unexpected exception thrown: " + ex.Message);
            }
        }
        
        [Test]
        public void Test_End_CalledTwice()
        {
            try
            {
                stateEnd._End();
                stateEnd._End();
                Assert.Fail("An exception should have been thrown"); 
            }
            catch (Exception ex)
            {
                Assert.IsInstanceOf<TypeOfTheExpectedException>(ex);
            }
        }

        // TODO: Add more test cases as necessary

        [TearDown]
        public void TearDown()
        {
            // TODO: Dispose any resources if needed
        }
    }
}
