// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using System;
using NUnit.Framework;
using FiniteStateMachine;
using Moq;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State_EndTest
    {
        private Mock<IFiniteStateMachine> _mockFiniteSateMachine;
        
        [SetUp]
        public void Initialize()
        {
            _mockFiniteSateMachine = new Mock<IFiniteStateMachine>(MockBehavior.Strict);
        }
        
        [TearDown]
        public void Cleanup()
        {
            _mockFiniteSateMachine.VerifyAll();
        }
        
        [Test]
        public void Basic_End_InvokesStateEnd()
        {
            // Arrange
            var testState = new State__End_5b00770643(_mockFiniteSateMachine.Object);

            _mockFiniteSateMachine.Setup(x => x.End());

            // Act
            testState._End();

            // Assert
            _mockFiniteSateMachine.Verify(x => x.End(), Times.Once);
        }

        [Test]
        public void End_CalledTwice_InvokesStateEndTwice()
        {
            // Arrange
            var testState = new State__End_5b00770643(_mockFiniteSateMachine.Object);

            _mockFiniteSateMachine.Setup(x => x.End());

            // Act
            testState._End();
            testState._End();

            // Assert
            _mockFiniteSateMachine.Verify(x => x.End(), Times.Exactly(2));
        }
    }
}
