// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateBeganEventArgs_FiniteStateBeganEventArgs_9169a2778c
    {
        private StateType stateType;

        [SetUp]
        public void Setup()
        {
            stateType = StateType.State1; // TODO: Change the stateType value according to test case
        }

        [Test]
        public void Constructor_OnValidStateType_SetsTypeCorrectly()
        {
            var stateBeganEventArgs = new FiniteStateBeganEventArgs(stateType);

            Assert.AreEqual(stateType, stateBeganEventArgs.Type);
        }

        [Test]
        public void Constructor_OnInvalidStateType_ThrowsException()
        {
            stateType = (StateType)999; // TODO: Change the stateType value to an invalid value according to your application

            Assert.Throws<ArgumentException>(() => new FiniteStateBeganEventArgs(stateType));
        }
    }
}
