// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class FiniteStateBeganEventArgs_FiniteStateBeganEventArgs_9169a2778c
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void FiniteStateBeganEventArgs_WithValidStateType_SetsStateTypeCorrectly()
        {
            // Arrange
            StateType expectedStateType = StateType.Valid;

            // Act
            var eventArgs = new FiniteStateBeganEventArgs(expectedStateType);

            // Assert
            Assert.AreEqual(expectedStateType, eventArgs.Type);
        }

        [Test]
        public void FiniteStateBeganEventArgs_WithInvalidStateType_ThrowsException()
        {
            // Arrange
            StateType invalidStateType = (StateType)1000; // TODO: Adjust to a value not defined in StateType enumeration

            // Act & Assert
            Assert.Throws<ArgumentException>(() => new FiniteStateBeganEventArgs(invalidStateType));
        }

        [Teardown]
        public void Teardown()
        {
            // TODO: Add necessary cleanup logic
        }
    }
}
