// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateMachine_Initialize_99e1f35a6a
    {
        private Mock<StateMachine> _stateMachine;

        [SetUp]
        public void Setup()
        {
            _stateMachine = new Mock<StateMachine>();
        }

        [Test]
        public void Initialize_WhenCalled_InvokesInitializeMethodOnStateMachine()
        {
            // Arrange
            _stateMachine.Setup(sm => sm.Initialize());

            // Act
            _stateMachine.Object.Initialize();

            // Assert
            _stateMachine.Verify(sm => sm.Initialize(), Times.Once());
        }

        [Test]
        public void Initialize_WhenExceptionThrown_PropagatesException()
        {
            // Arrange
            _stateMachine
                .Setup(sm => sm.Initialize())
                .Throws(new Exception("Test exception"));

            // Assert
            Assert.Throws<Exception>(() => _stateMachine.Object.Initialize());
        }

        [TearDown]
        public void Cleanup()
        {
            _stateMachine = null;
        }
    }
}
