// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Tests
{
    [TestFixture]
    public class StateMachine_Initialize_99e1f35a6a
    {
        private StateMachine _stateMachine;

        [SetUp]
        public void Setup()
        {
            _stateMachine = new StateMachine(); // TODO Change the instantiation if needed.
        }

        [Test]
        public void Initialize_StateMachineInitialized_Succeeds()
        {
            // Arrange
            // Nothing to arrange for this test 

            // Act
            TestDelegate initializeDelegate = () => _stateMachine.Initialize();

            // Assert
            Assert.DoesNotThrow(initializeDelegate, "Expected Initialize to not throw any exceptions, but it did.");
        }

        [Test]
        public void Initialize_StateMachineAlreadyInitialized_ThrowsException()
        {
            // Arrange
            _stateMachine.Initialize();

            // Act
            TestDelegate initializeDelegate = () => _stateMachine.Initialize();

            // Assert
            Assert.Throws<InvalidOperationException>(initializeDelegate, "Expected Initialize to throw InvalidOperationException when called second time, but it didn't.");
        }

        [TearDown]
        public void TearDown()
        {
            _stateMachine = null; // Clean-up the stateMachine object.
        }
    }
}
