// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using System;
using NUnit.Framework;
using Moq;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateBase__End_3643a6cf0d
    {
        private FiniteStateMachine.StateBase _stateBase;
        private Mock<IFiniteStateMachine> _finiteStateMachine;

        [SetUp]
        public void Setup()
        {
            _finiteStateMachine = new Mock<IFiniteStateMachine>();
            _stateBase = new FiniteStateMachine.StateBase
            {
                Instance = _finiteStateMachine.Object
            };
        }

        [Test]
        public void Test_End_ShouldInvokeEndMethod()
        {
            _stateBase._End();
            _finiteStateMachine.Verify(fsm => fsm.End(), Times.Once);
        }

        [Test]
        public void Test_End_ShouldInvokeOnStateEndedEvent()
        {
            var isEventTriggered = false;
            _stateBase.OnStateEnded += (o, e) => isEventTriggered = true;

            _stateBase._End();

            Assert.That(isEventTriggered, Is.True);
        }
    }
}
