// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachine_Update_97a3df38bc
    {
        private FiniteStateMachine finiteStateMachine;

        [SetUp]
        public void SetUp()
        {
            this.finiteStateMachine = new FiniteStateMachine();
        }

        [Test]
        public void Update_WithPositiveDeltaTime_ExpectMethodExecuteWithoutException()
        {
            float deltaTime = 1f;

            Assert.DoesNotThrow(() => finiteStateMachine.Update(deltaTime));
        }

        [Test]
        public void Update_WithZeroDeltaTime_ExpectMethodExecuteWithoutException()
        {
            float deltaTime = 0;

            Assert.DoesNotThrow(() => finiteStateMachine.Update(deltaTime));
        }

        [Test]
        public void Update_WithNegativeDeltaTime_ExpectMethodExecuteWithoutException()
        {
            float deltaTime = -1f;

            Assert.DoesNotThrow(() => finiteStateMachine.Update(deltaTime));
        }

        // Consider adding more test cases to test the behavior of the function after execution.
        // This would be possible if the method was performing some operation that can be checked in the test cases.

        [TearDown]
        public void TearDown()
        {
            // TODO: Add code to clean up after tests if necessary
        }
    }
}
