// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachine_Update_97a3df38bc
    {
        private MyFiniteStateMachine finiteStateMachine;

        [SetUp]
        public void SetUp()
        {
            finiteStateMachine = new MyFiniteStateMachine();
        }
        
        [Test]
        public void Update_ValidDeltaTime_StateMachineUpdatedSuccessfully()
        {
            // Arrange
            float deltaTime = 1.0F;
            
            // Act
            finiteStateMachine.Update(deltaTime);
            
            // Assertion is in the form of 'Expected vs Actual'
            // Since the method does not return anything, traditional assertion may not be possible
            // We could assert based on changes that happen in the object due to Update method
            // TODO: provide the expected change after calling the Update method.
        }

        [Test]
        public void Update_NegativeDeltaTime_ThrowsException()
        {
            // Arrange
            float deltaTime = -1.0F;
            
            // Act & Assert
            // TODO: Replace the typeof(Exception) with the actual type of the exception expected to be thrown.
            Assert.Throws(typeof(Exception), () => finiteStateMachine.Update(deltaTime));
        }

        [Test]
        public void Update_ZeroDeltaTime_ThrowsExceptionOrNot()
        {
            // Arrange
            float deltaTime = 0;
            
            // Act
            finiteStateMachine.Update(deltaTime);
            
            // Assertion
            // TODO: Add appropriate assertions.
        }

        [TearDown]
        public void TearDown()
        {
            finiteStateMachine = null;
        }
    }
}
