// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Moq;

namespace FiniteStateMachine.Test
{
    public class StateMachine_Update_73a5496b2c
    {
        private Mock<IState> _mockState;

        [SetUp]
        public void Setup()
        {
            _mockState = new Mock<IState>();
        }

        // Test with m_currentState not null
        [Test]
        public void Update_WithState_CallsUpdate()
        {
            // Arrange
            var stateMachine = new StateMachine();
            stateMachine.m_currentState = _mockState.Object;

            // Act
            stateMachine.Update(1.0f);

            // Assert
            _mockState.Verify(s => s._Update(1.0f), Times.Once);
        }

        // Test with m_currentState is null
        [Test]
        public void Update_WithoutState_DoNotThrowException()
        {
            // Arrange
            var stateMachine = new StateMachine();
            stateMachine.m_currentState = null;

            // Act
            TestDelegate act = () => stateMachine.Update(1.0f);

            // Assert
            Assert.DoesNotThrow(act);
            _mockState.Verify(s => s._Update(It.IsAny<float>()), Times.Never);
        }
    }
}
