// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using System;
using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    public class StateBase__Update_8c1484250fTest
    {
        private StateBase__Update_8c1484250f _stateBase;

        [SetUp]
        public void Setup()
        {
            _stateBase = new StateBase__Update_8c1484250f(); 
            // TODO: Initialize _stateBase with valid parameters.
        }

        [Test]
        public void _Update_CalledWithPositiveFloat_UpdatesNormally()
        {
            float dt = 5.0f;
            Assert.DoesNotThrow(() => _stateBase._Update(dt));
        }

        [Test]
        public void _Update_CalledWithZero_UpdatesNormally()
        {
            float dt = 0.0f;
            Assert.DoesNotThrow(() => _stateBase._Update(dt));
        }

        [Test]
        public void _Update_CalledWithNegativeFloat_ThrowsArgumentException()
        {
            float dt = -1.0f;
            Assert.Throws<ArgumentException>(() => _stateBase._Update(dt));
        }

        [TearDown]
        public void Teardown()
        {
            _stateBase = null;
        }
    }
}
