// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test {
    public class FiniteStateMachine_FiniteStateMachine_4ac7eeddda {
        // Define test object
        private FiniteStateMachine fsm;

        // Use SetUp to instantiate test object before each
        // test method is run
        [SetUp]
        public void SetUp() {
            fsm = new FiniteStateMachine();
        }

        // A test case for normal usage
        [Test]
        public void FiniteStateMachine_NormalUsage_Success() {
            Assert.DoesNotThrow(() => new FiniteStateMachine());
        }

        // A test case for verifying if instance can be reused
        [Test]
        public void FiniteStateMachine_InstanceReusability_Success() {
            Assert.DoesNotThrow(() => fsm = new FiniteStateMachine());
        }

        // A test case to verify if multiple instances can be created
        [Test]
        public void FiniteStateMachine_MultipleInstanceCreation_Success() {
            Assert.DoesNotThrow(() => {
                FiniteStateMachine fsm1 = new FiniteStateMachine();
                FiniteStateMachine fsm2 = new FiniteStateMachine();
            });
        }

        // Use TearDown to clean up any resources after each
        // test method is run
        [TearDown]
        public void TearDown() {
            // Dispose/Reset fsm here, if necessary
            fsm = null;
        }
    }
}
