// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using System;
using NUnit.Framework;
using FiniteStateMachine;
using FiniteStateMachine.Test;
using Moq;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachine_FiniteStateMachine_4ac7eeddda
    {
        private FiniteStateMachine _sut;

        [SetUp]
        public void SetUp()
        {
            _sut = new FiniteStateMachine();
        }

        [Test]
        public void FiniteStateMachine_Instantiated_Successfully()
        {
            // Arrange
            int expectedStatesCount = 0;

            // Act
            int actualStatesCount = _sut.StatesCount;

            // Assert
            Assert.AreEqual(expectedStatesCount, actualStatesCount, "Finite State Machine was not instantiated correctly");
        }

        [Test]
        public void FiniteStateMachine_Throws_Exception_When_Null_Input_Is_Passed()
        {
            // Arrange
            string nullInput = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => _sut.ProcessInput(nullInput), "Finite State Machine did not throw exception for null input");
        }
        
        [TearDown]
        public void TearDown()
        {
            _sut = null;
        }
    }
}
