// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine.Test;
using System;

namespace FiniteStateMachine.Test
{
    public class StateBase_StateBase_87eb67ac37
    {
        private FiniteStateMachine _fsm;
        private StateType _stateKey;

        [SetUp]
        public void Setup()
        {
            _fsm = new FiniteStateMachine();
            _stateKey = StateType.StateKey;
        }

        [Test]
        public void StateBase_ValidParameter_ReturnsStateBase()
        {
            // Arrange
            var stateBase = new StateBase(_fsm, _stateKey);

            // Act
            var result = stateBase;

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(_fsm, result.FiniteStateMachine);
            Assert.AreEqual(_stateKey, result.StateKey);
        }

        [Test]
        public void StateBase_NullParameter_ThrowsArgumentNullException()
        {
            // Arrange
            FiniteStateMachine nullFsm = null;
            StateType nullStateKey = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new StateBase(nullFsm, _stateKey));
            Assert.Throws<ArgumentNullException>(() => new StateBase(_fsm, nullStateKey));
        }
    }
}
