// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using FiniteStateMachine.Test;
using System;

namespace FiniteStateMachine.Test
{
    public class StateBase_StateBase_87eb67ac37
    {
        private FiniteStateMachine _finiteStateMachine;

        [SetUp]
        public void Setup()
        {
            _finiteStateMachine  = new FiniteStateMachine();
        }

        [Test]
        public void StateBase_ConstructorWithValidParameters_ShouldNotThrowException()
        {
            Assert.DoesNotThrow(() => {
                StateBase stateBase = new StateBase(_finiteStateMachine, StateType.New); 
            });
        }

        [Test]
        public void StateBase_ConstructorWithNullFiniteStateMachine_ShouldThrowArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => {
                StateBase stateBase = new StateBase(null, StateType.New); 
            });
        }

        [Test]
        public void StateBase_ConstructorWithInvalidStateType_ShouldThrowArgumentException()
        {
            Assert.Throws<ArgumentException>(() => {
                // TODO: replace InvalidStateType with an invalid state type according your scenario
                StateBase stateBase = new StateBase(_finiteStateMachine, InvalidStateType); 
            });
        }
    }
}
