// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateEndedEventArgs_Tests
    {
        [Test]
        public void Constructor_Sets_Type_To_Input_StateType()
        {
            // Arrange
            StateType inputStateType = StateType.Running;

            // Act
            var finiteStateEndedEventArgs = new FiniteStateEndedEventArgs(inputStateType);
            
            // Assert
            Assert.AreEqual(inputStateType, finiteStateEndedEventArgs.Type);
        }

        [Test]
        public void Constructor_Sets_Type_To_Default_If_Input_Is_Null()
        {
            // Arrange
            StateType inputStateType = null;

            // Act
            var finiteStateEndedEventArgs = new FiniteStateEndedEventArgs(inputStateType);
            
            // Assert
            Assert.AreEqual(default(StateType), finiteStateEndedEventArgs.Type);
        }
    }
}
