// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateEndedEventArgsTest
    {
        [Test]
        public void FiniteStateEndedEventArgs_StateTypeEnded_ShouldSetTypePropertyAsEndedState()
        {
            //Arrange
            var expectedState = new StateType() { Name = "Ended"};

            //Act
            var result = new FiniteStateEndedEventArgs(expectedState);

            //Assert
            Assert.That(result.Type, Is.EqualTo(expectedState));
        }

        [Test]
        public void FiniteStateEndedEventArgs_NullEndedState_ShouldThrowArgumentNullException()
        {
            //Arrange
            StateType nullState = null;

            //Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateEndedEventArgs(nullState));
        }
    }
}
