// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;
using Moq;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateMachine_Initialize_df35803478 
    {
        private FiniteStateMachine finiteStateMachine;
        private Mock<FiniteStateMachine> mockFiniteStateMachine;

        [SetUp]
        public void Setup() 
        {
            finiteStateMachine = new FiniteStateMachine();
            mockFiniteStateMachine = new Mock<FiniteStateMachine>() { CallBase = true };
        }

        [Test]
        public void Initialize_WhenCalled_ShouldRunWithoutExceptions()
        {
            // Arrange
            // Nothing to arrange in this case.
            
            // Act
            TestDelegate action = () => finiteStateMachine.Initialize();

            // Assert
            Assert.DoesNotThrow(action);
        }

        [Test]
        public void Initialize_WhenCalled_InvokesBaseInitialize()
        {
            // Arrange
            mockFiniteStateMachine.Setup(x => x.Initialize());
            
            // Act
            TestDelegate action = () => mockFiniteStateMachine.Object.Initialize();

            // Assert
            Assert.DoesNotThrow(action);
            mockFiniteStateMachine.Verify(m => m.Initialize(), Times.Once);
        }

        [TearDown]
        public void Teardown() 
        {
            finiteStateMachine = null;
            mockFiniteStateMachine = null;
        }
    }
}
