// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateBase__Begin_1ebf58b534_Test
    {
        [Test]
        public void Begin_WithValidParams_BeganEventTriggered()
        {
            bool beganEventTriggered = false;
            FiniteStateMachine.Instance.OnStateBegan += (args) => beganEventTriggered = true;
            var stateBase = new SomeStateBase();
            var eventArgs = new FiniteStateChangeEventArgs();
            var previousStateKey = new StateType();

            stateBase._Begin(eventArgs, previousStateKey);
            
            Assert.IsTrue(beganEventTriggered);
        }

        [Test]
        public void Begin_WithNullEventArgs_BeganEventTriggered()
        {
            bool beganEventTriggered = false;
            FiniteStateMachine.Instance.OnStateBegan += (args) => beganEventTriggered = true;
            var stateBase = new SomeStateBase();
            var previousStateKey = new StateType();

            stateBase._Begin(null, previousStateKey);
            
            Assert.IsTrue(beganEventTriggered);
        }

        [Test]
        public void Begin_WithNullPrevStateKey_BeganEventTriggered()
        {
            bool beganEventTriggered = false;
            FiniteStateMachine.Instance.OnStateBegan += (args) => beganEventTriggered = true;
            var stateBase = new SomeStateBase();
            var eventArgs = new FiniteStateChangeEventArgs();

            stateBase._Begin(eventArgs, null);
            
            Assert.IsTrue(beganEventTriggered);
        }
    }
}
