// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using Moq;

namespace FiniteStateMachine.Test
{
    public class State__Begin_bae0ee3e61 
    {
        private Mock<State> _stateMock;
        private FiniteStateChangeEventArgs _eventArgs;
        private int _previousStateKey;

        [SetUp]
        public void Setup()
        {
            _stateMock = new Mock<State>();
            _eventArgs = new FiniteStateChangeEventArgs();
            _previousStateKey = 1;
        }
     
        [Test]
        public void Test_Begin_ShouldCallBaseClassFunction_WhenCalled()
        {
            //Act
            _stateMock.Object.Begin(_eventArgs, _previousStateKey);

            //Assert
            _stateMock.Verify(x => x.Begin(_eventArgs, _previousStateKey));
        }

        [Test]
        public void Test_Begin_ShouldCallBaseFunctionOnce_WhenCalled()
        {
            //Act
            _stateMock.Object.Begin(_eventArgs, _previousStateKey);

            //Assert
            _stateMock.Verify(x => x.Begin(_eventArgs, _previousStateKey), Times.Once());
        }
     
        [TearDown]
        public void CleanUp()
        {
            // Clean up resources
            _stateMock = null;
            _eventArgs = null;
            _previousStateKey = 0;
        }
    }
}
