// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using Rhino.Mocks;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State__Begin_bae0ee3e61
    {
        private IFiniteStateChangeEventArgs _eventArgs;
        private IFiniteState _finiteState;
        private int _previousStateKey;

        [SetUp]
        public void Setup()
        {
            _eventArgs = MockRepository.GenerateMock<IFiniteStateChangeEventArgs>();
            _finiteState = MockRepository.GenerateMock<IFiniteState>();
            _previousStateKey = 1;
        }

        [Test]
        public void Test_Begin_ValidArgs_InvokesBegin()
        {
            _finiteState.Expect(fs => fs.Begin(_eventArgs, _previousStateKey));
            _finiteState._Begin(_eventArgs, _previousStateKey);
            _finiteState.VerifyAllExpectations();
        }

        [Test]
        public void Test_Begin_NullEventArgs_ThrowsException()
        {
            Assert.That(() => _finiteState._Begin(null, _previousStateKey), Throws.ArgumentNullException);
        }

        [Test]
        public void Test_Begin_NegativePreviousStateKey_ThrowsException()
        {
            Assert.That(() => _finiteState._Begin(_eventArgs, -1), Throws.ArgumentException);
        }

        [TearDown]
        public void Teardown()
        {
            _finiteState = null;
            _eventArgs = null;
            _previousStateKey = 0;
        }
    }
}
