// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateBeganEventArgs_FiniteStateChangeEventArgs_08e3fe74ea
    {
        [Test]
        public void StateChangeEventArgs_RequestedStateIsSet_StateTypeMatchesInput()
        {
            // arrange
            var requestedState = StateType.Open;
            var stateInfo = new StateInfo();

            // act
            var args = new FiniteStateChangeEventArgs(requestedState, stateInfo);

            // assert
            Assert.AreEqual(requestedState, args.RequestedType);
        }

        [Test]
        public void StateChangeEventArgs_StateInfoIsSet_StateInfoMatchesInput()
        {
            // arrange
            var requestedState = StateType.Open;
            var stateInfo = new StateInfo();

            // act
            var args = new FiniteStateChangeEventArgs(requestedState, stateInfo);

            // assert
            Assert.AreEqual(stateInfo, args.StateInfo);
        }

        [Test]
        public void StateChangeEventArgs_RequestIsNull_ThrowsArgumentNullException()
        {
            // arrange
            StateType? requestedState = null;
            var stateInfo = new StateInfo();

            // assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(requestedState, stateInfo));
        }

        [Test]
        public void StateChangeEventArgs_StateInfoIsNull_ThrowsArgumentNullException()
        {
            // arrange
            var requestedState = StateType.Open;
            StateInfo stateInfo = null;

            // assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(requestedState, stateInfo));
        }
    }
}
