// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using FiniteStateMachine;
using System.Collections.Generic;

namespace FiniteStateMachine.Tests
{
    [TestFixture]
    public class StateMachine_MoveTo_c8325e5825
    {
        private FiniteStateMachine<T> _finiteStateMachine;

        [SetUp]
        public void SetUp()
        {
            // TODO: Substitute with real data
            Dictionary<T, State<T>> states = new Dictionary<T, State<T>>();
            _finiteStateMachine = new FiniteStateMachine<T>(states);
        }

        [Test]
        public void MoveTo_ValidTargetState_ReturnsTargetStateKey()
        {
            // Arrange
            T targetStateKey = /* TODO: Substitute with real data */ default(T);
            _finiteStateMachine.AddState(targetStateKey, new State<T>(targetStateKey));

            // Act
            T result = _finiteStateMachine.MoveTo(targetStateKey);

            // Assert
            Assert.AreEqual(targetStateKey, result);
        }

        [Test]
        public void MoveTo_NullTargetState_ThrowsException()
        {
            // Arrange
            T targetStateKey = /* TODO: Substitute with real data */ null;

            // Assert
            Assert.Throws<Exception>(() => _finiteStateMachine.MoveTo(targetStateKey);
        }

        [Test]
        public void MoveTo_NonexistentState_ThrowsException()
        {
            // Arrange
            T targetStateKey = /* TODO: Substitute with real data */ default(T);

            // Assert
            Assert.Throws<Exception>(() => _finiteStateMachine.MoveTo(targetStateKey);
        }

        [TearDown]
        public void TearDown()
        {
            _finiteStateMachine = null;
        }
    }
}
